const $ = id => document.getElementById(id);
const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pit = n => `PIT-${String(n).padStart(3,'0')}`;
$('revision').textContent = `${report.version} · Evidence checkpoint ${report.cutoff}`;
$('findingCount').textContent=report.findings.length;
$('highCount').textContent=report.findings.filter(f=>['Critical','High'].includes(f[0])).length;
$('scenarios').innerHTML=report.scenarios.map(([n,title,done,todo])=>`<tr id="scenario-${n}"><td>${pit(n)}<br>${esc(title)}<br><span class="history">PARTIAL · ${n<=6?'Reused eligible prior run':'Current run + appendices'}</span></td><td>${esc(done)}</td><td>${esc(todo)}</td><td><div class="cells">${report.sizes.map(s=>`<span>${s} · incomplete</span>`).join('')}</div></td></tr>`).join('');
$('gaps').innerHTML=report.gaps.map(([title,scope,body])=>`<article><h3>${esc(title)}</h3><small>${esc(scope)}</small><p>${esc(body)}</p></article>`).join('');
function filtered(){const q=$('search').value.toLowerCase();return report.findings.map((f,i)=>({f,id:`PIT-F${String(i+1).padStart(3,'0')}`})).filter(({f,id})=>(!$('severity').value||f[0]===$('severity').value)&&(!$('status').value||f[6]===$('status').value)&&`${id} ${f.flat().join(' ')} ${f[1].map(pit).join(' ')}`.toLowerCase().includes(q));}
function render(){const rows=filtered();$('match').textContent=`${rows.length} of ${report.findings.length} findings shown · Expand any row for details`;$('register').innerHTML=rows.map(({f:[severity,ids,title,steps,actual,expected,status],id})=>`<details id="${id}"><summary><span class="badge ${severity}">${severity}</span><span class="finding-title">${esc(title)}<span class="meta">${id} · ${ids.map(pit).join(' / ')} · ${esc(status)} · Unresolved</span></span></summary><div class="detail"><p><strong>Reproduction / observed path</strong>${esc(steps)}</p><p><strong>Actual result</strong>${esc(actual)}</p><p><strong>Expected result / acceptance</strong>${esc(expected)}</p><p><strong>Provenance</strong>11 September campaign record or eligible reused run. See ${ids.map(n=>`<a href="#scenario-${n}">${pit(n)} scenario</a>`).join(', ')} and private numbered scenario runs/appendices. This public entry is a sanitized consolidation, not the full raw execution log.</p><p><strong>Fix / retest</strong>No fix verified in this publication. Preserve original evidence, record the fix revision, then append independent browser retest results and exact viewport scope.</p><a href="#${id}">Link to finding</a></div></details>`).join('')||'<p>No findings match these filters.</p>';}
['search','severity','status'].forEach(id=>$(id).addEventListener('input',render));$('reset').onclick=()=>{['search','severity','status'].forEach(id=>$(id).value='');render();};
const csvCell=s=>'"'+String(s).replace(/"/g,'""')+'"';
$('export').onclick=()=>{const rows=[['ID','Severity','Scenarios','Title','Reproduction','Actual','Expected','Evidence status','Fix status'],...filtered().map(({f,id})=>[id,f[0],f[1].map(pit).join(' / '),f[2],f[3],f[4],f[5],f[6],'Unresolved; not retested'])];const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='pitcher-uat-interim-findings-20260911.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
render();function openHash(){const el=document.getElementById(location.hash.slice(1));if(el?.tagName==='DETAILS')el.open=true;}addEventListener('hashchange',openHash);openHash();
